### ISSUE TITLE
Suggest: Webhook notifications

### ISSUE THREAD

**Issue by SploeCyber** [noto-rious/Nitro.Self-V3#1]
:)

**Comment by noto-rious** [comment]
This is doable, I'll see if I can roll this feature out sometime tomorrow.

**Comment by noto-rious** [comment]
![testing](https://user-images.githubusercontent.com/69278774/96330668-be229c00-101c-11eb-9fa7-747701220145.png)
I've set it up so that you can optionally log failed events, this is the webhook output embed I've come up with. Just looking for bugs before I release this.

**Comment by SploeCyber** [comment]
It looks really cool 😮

**Comment by noto-rious** [comment]
> It looks really cool 😮

![image](https://user-images.githubusercontent.com/69278774/96335163-0dc49000-103c-11eb-9a85-5c12a9bc25a1.png)

Thanks heres another look with some more changes made, the top webhook embed is from a server event while the bottom one is from a direct message event.

**Comment by noto-rious** [comment]
Alright this feature has been released, should you happen to find any bugs or have any more suggestions you can open a new issue or contact me on Discord(my contact info can be found on my main profile readme). Thanks for the suggestion and I hope you enjoy!
