### ISSUE TITLE
Error message "New subscription required to redeem gift"

### ISSUE THREAD

**Issue by gitmadub** [noto-rious/Nitro.Self-V3#12]
The thing is I currently have a active subscription...

https://prnt.sc/wg5c7j
https://prnt.sc/wg5eor

**Comment by noto-rious** [comment]
> 
> 
> The thing is I currently have a active subscription...
> 
> https://prnt.sc/wg5c7j
> https://prnt.sc/wg5eor

Yeah this somehow ties into issue #8, I'm still unsure about that specific response but generally it seems that these codes somehow tie into the microsoft.com/redeem promo and can be for the most part ignored as they are not normal gifts. However that's pure speculation on my end for the time being. I will continue to investigate until I encounter that response myself and can find a prominent answer.

**Comment by noto-rious** [comment]
I will add this, I was able to redeem one of those codes via the sniper, in my situation however I had no active subscription.

**Comment by noto-rious** [comment]
> 
> 
> I will add this, I was able to redeem one of those codes via the sniper, in my situation however I had no active subscription.

and once you redeem one of these codes you can not redeem them again, it will return an already purchased response.

**Comment by gitmadub** [comment]
Ok thanks for your response :) 👍

**Comment by noto-rious** [comment]
> 
> 
> Ok thanks for your response :) 👍

yeah and now that i'm thinking about the response. i think what it is trying to say is that since you have an exisiting subscription, you can not create a new subscription so maybe it is indeed trying to tell you to cancel the subscription(which just cancels the auto renew).

**Comment by gitmadub** [comment]
> 
> 
> > Ok thanks for your response :) 👍
> 
> yeah and now that i'm thinking about the response. i think what it is trying to say is that since you have an exisiting subscription, you can not create a new subscription so maybe it is indeed trying to tell you to cancel the subscription(which just cancels the auto renew).

Mhh ok. Some time ago I was able to redeem a gift manually although the auto renew was active. Maybe its just a API thing... I have now canceled the auto renew.

**Comment by noto-rious** [comment]
> 
> 
> > > Ok thanks for your response :) 👍
> > 
> > 
> > yeah and now that i'm thinking about the response. i think what it is trying to say is that since you have an exisiting subscription, you can not create a new subscription so maybe it is indeed trying to tell you to cancel the subscription(which just cancels the auto renew).
> 
> Mhh ok. Some time ago I was able to redeem a gift manually although the auto renew was active. Maybe its just a API thing... I have now canceled the auto renew.

Yeah, please let me know if you end up getting a 3 month credit or a different response code. I'm trying to document this as much as I can.

**Comment by noto-rious** [comment]
Any change? Still getting the error?

**Comment by gitmadub** [comment]
> 
> 
> Any change? Still getting the error?

I got this message only one time. All other (before & after) are only "Code has already beed redeemed" ^^
Its now running around two weeks but no luck until now :/

**Comment by gitmadub** [comment]
> > Ok thanks for your response :) 👍
> 
> yeah and now that i'm thinking about the response. i think what it is trying to say is that since you have an exisiting subscription, you can not create a new subscription so maybe it is indeed trying to tell you to cancel the subscription(which just cancels the auto renew).

Today I got the same message again with auto renew disabled.
https://prnt.sc/wjf50o
I now re-enabled the auto renew.

**Comment by noto-rious** [comment]
> 
> 
> > > Ok thanks for your response :) 👍
> > 
> > 
> > yeah and now that i'm thinking about the response. i think what it is trying to say is that since you have an exisiting subscription, you can not create a new subscription so maybe it is indeed trying to tell you to cancel the subscription(which just cancels the auto renew).
> 
> Today I got the same message again with auto renew disabled.
> https://prnt.sc/wjf50o
> I now re-enabled the auto renew.

Hey thank you so much for the reply. This is kind of what I figured what would happen. Seems that you can't have any current Nitro on the account at all if you want to redeem those promotional codes. Not much that can be done about that on my end but I will be casing the situations out to give a more detailed explaination to the user. I will close this now and reference the issue when I push the build.
