### ISSUE TITLE
Not a bug but question

### ISSUE THREAD

**Issue by l29** [noto-rious/Nitro.Self-V3#18]
Not a bug but can you say me where you get that Ascii from

**Comment by noto-rious** [comment]
https://github.com/xero/figlet-fonts/blob/master/Bloody.flf

**Comment by noto-rious** [comment]
https://github.com/xero/figlet-fonts/blob/master/Bloody.flf

**Comment by noto-rious** [comment]
or you can use this site if you don't have figlet http://www.patorjk.com/software/taag/#p=display&f=Bloody&t=Type%20Something%20
