### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by SploeCyber** [noto-rious/Nitro.Self-V3#3]
version: 3.2.6
Here is logs:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xeba2ed]

goroutine 314 [running]:
github.com/itsTurnip/dishooks.(*Webhook).URL(...)
        C:/Users/Notorious/go/pkg/mod/github.com/its!turnip/dishooks@v0.0.0-20200206125049-b4fc7c7b042e/webhook.go:107
github.com/itsTurnip/dishooks.(*Webhook).Get(0x0, 0x78, 0x0)
        C:/Users/Notorious/go/pkg/mod/github.com/its!turnip/dishooks@v0.0.0-20200206125049-b4fc7c7b042e/webhook.go:113 +0x2d
main.sWebhook(0xc000060080, 0x78, 0x103ace2, 0x9, 0x104ea68, 0x3c, 0xc000dc0400, 0x3d, 0x1, 0xc000dbb2d0, ...)
        C:/Users/Notorious/Documents/GoLang Testing/New folder/sniper.go:411 +0x95e
main.(*Thread).MessageCreate.func1(0xc0000c8d08, 0xc000062240, 0xc000cc6600, 0xc00001e480)
        C:/Users/Notorious/Documents/GoLang Testing/New folder/sniper.go:556 +0x423e
created by main.(*Thread).MessageCreate
        C:/Users/Notorious/Documents/GoLang Testing/New folder/sniper.go:422 +0x8a`

**Comment by noto-rious** [comment]
Any tip you can give me any tips on how you replicate the panic?

**Comment by SploeCyber** [comment]
> Any tip you can give me any tips on how you replicate the panic?

It happened after sending a fails report to webhook

**Comment by noto-rious** [comment]
Are you running the binary version or the go version? Have you used go.mod to install the dependencies?(only applies to source version)

**Comment by SploeCyber** [comment]
binary version

**Comment by noto-rious** [comment]
And have you tried rebuilding from the source? Same result? I'll have to see if I can replicate this issue on my end can you tell me what OS you're using?

**Comment by noto-rious** [comment]
Also double check that your are using a proper webhook url.

**Comment by SploeCyber** [comment]
I have tried build from source and it solved this problem.  It could have been caused by my incomplete download of the file

**Comment by noto-rious** [comment]
Thanks for replying with the solution. I have also taken some of your advice and recompiled the binaries on my end. Feel tree to open another ticket if you have any other issues.
