### ISSUE TITLE
error opening connection, websocket: close 4004: Authentication failed.

### ISSUE THREAD

**Issue by AllinolCP** [noto-rious/Nitro.Self-V3#4]
^

**Comment by AllinolCP** [comment]
this happened when you copy the token from windows using FTP

**Comment by AllinolCP** [comment]
apparently the issue got caused by the token being invalid that is sent by the science page, thanks

**Comment by noto-rious** [comment]
> 
> 
> apparently the issue got caused by the token being invalid that is sent by the science page, thanks

Just to clarify here, the token returned from the science page in the returned json payload is not the correct token, what you are looking for is an authorization header and not a payload, the value of the authorization header is the token that you need.
