### ISSUE TITLE
1 second delay

### ISSUE THREAD

**Issue by prifin** [noto-rious/Nitro.Self-V3#5]
Hello, 
I have got 1 second delay from sniping a nitro.
It said discord nitro already claimed Delay: 1,..seconds.
I forgot to screenshot but basically the delay was bigger than 1 second
Do you know any reason why this happened cuz as i see on the picture the delay is around 200ms.
Thank You

**Comment by noto-rious** [comment]
Sorry, I misread your message I think I comprehend what you are saying now. In the future, if you run into this issue again can you supply me with the gift code(my contact info can be found on my landing page), and hopefully I can replicate the issue and create a fix.

But I honestly get some 900ms pings myself here and there, I chalk it up to server hiccups, or networking issues as it doesn't happen frequently.

**Comment by prifin** [comment]
Hi,
Now im getting around 200ms delay so its okay now.
Thank You
