### ISSUE TITLE
Sniping on main account false

### ISSUE THREAD

**Issue by prifin** [noto-rious/Nitro.Self-V3#6]
Hello,
When i change "snipe_on_main" to false, program crashes right after opening.
Is there something i have to add to make it work?
Thank You

**Comment by noto-rious** [comment]
I'll look into this and get back to you. Also double double the formatting and make sure it it is plainly just 0 or false rather than "0" or "false"

**Comment by prifin** [comment]
It is set to just false, but im wondering, if i set it to false, there has to be a field for the main account token for reedem doesn't it?

**Comment by noto-rious** [comment]
> 
> 
> It is set to just false, but im wondering, if i set it to false, there has to be a field for the main account token for reedem doesn't it?

Indeed, if this is the case and you do not at least have the main token filled out it will not work properly. It uses that token to authorize the redeems to the main account.

**Comment by prifin** [comment]
yes, but i cant find where do i have to put the main account token

**Comment by noto-rious** [comment]
> 
> 
> yes, but i cant find where do i have to put the main account token

![image](https://user-images.githubusercontent.com/69278774/101243259-83f08500-36c4-11eb-95e5-ec40c4bb0b61.png)

there's a documentation README.md explaining how the configuration works as well as where to get the token.

**Comment by prifin** [comment]
so main doesnt mean sniping account token?

**Comment by noto-rious** [comment]
> 
> 
> so main doesnt mean sniping account token?

it does.

**Comment by prifin** [comment]
okay, can i then somehow reedem the sniped token on other account?

**Comment by noto-rious** [comment]
> 
> 
> okay, can i then somehow reedem the sniped token on other account?

If you are asking if each bot can redeem on its own token then no, this is setup to maximize the odds of getting nitro on 1 account.

Further more: if you are wishing to disable sniping on main and use other accounts simply paste those accounts tokens in tokens.txt These are what I call worker accounts and just look for the codes, all the codes get redeemed to the main account tho.

**Comment by prifin** [comment]
Oh thats what i wanted to know. So when i put my main account token in Token field, disable the sniping on main and put bot accounts into tokens.txt, i will snipe on bot accounts but reedem on main? Am i understanding it right?

**Comment by noto-rious** [comment]
> 
> 
> Oh thats what i wanted to know. So when i put my main account token in Token field, disable the sniping on main and put bot accounts into tokens.txt, i will snipe on bot accounts but reedem on main? Am i understanding it right?

100% correct.

**Comment by prifin** [comment]
Very good, Thank You man!

**Comment by noto-rious** [comment]
> 
> 
> Very good, Thank You man!

No problem. Thank you for taking the time to check out my work.
