### ISSUE TITLE
Unrelated, but

### ISSUE THREAD

**Issue by nions-ops** [noto-rious/Nitro.Self-V3#8]
So sorry if this isn't meant for issues, but I have a question.

![image](https://user-images.githubusercontent.com/71730062/101534786-89600080-394c-11eb-9989-c6b73c2d3c22.png)

It seems Discord is requiring a payment source now? I do have Nitro on my account but no matter what, the "valid" codes always require a payment source. Before, it wasn't like this, these codes would count as Nitro "credit"

Is this a new anti-sniping feature to get the payment info of accounts?

**Comment by noto-rious** [comment]
> 
> 
> So sorry if this isn't meant for issues, but I have a question.
> 
> ![image](https://user-images.githubusercontent.com/71730062/101534786-89600080-394c-11eb-9989-c6b73c2d3c22.png)
> 
> It seems Discord is requiring a payment source now? I do have Nitro on my account but no matter what, the "valid" codes always require a payment source. Before, it wasn't like this, these codes would count as Nitro "credit"
> 
> Is this a new anti-sniping feature to get the payment info of accounts?

As far as I can tell this is some sort of new anti-sniping feature. Sadly don't know of any way around it other than to attach a valid payment source. I will leave this issue open for awhile on the off chance someone has more knowledge on it than I do.

**Comment by noto-rious** [comment]
I have made some changes to the JSON payload that would properly reflect manually redeeming a code on Discord. Basically I nulled their values out. I haven't gotten any more reports on this error response from the people that were helping me pe-test this build. I will leave this open for a few more days just to confirm with the rest of the community here. See the latest release (3.2.9) to test the changes.

**Comment by razzviruz** [comment]
![image](https://user-images.githubusercontent.com/39065366/102014519-ac2c5380-3d56-11eb-8d41-e2b932b3ff02.png)
i hope it works and not for 5 years waiting xD

**Comment by nions-ops** [comment]
> ![image](https://user-images.githubusercontent.com/39065366/102014519-ac2c5380-3d56-11eb-8d41-e2b932b3ff02.png)
> i hope it works and not for 5 years waiting xD

Same here, going to test. Thanks for the fix however!

**Comment by noto-rious** [comment]
Got bad news this morning, the issue still persists for some. The last release was kind of a last ditch effort so I'm just kind of scratching my head.

**Comment by nions-ops** [comment]
> Got bad news this morning, the issue still persists for some. The last release was kind of a last ditch effort so I'm just kind of scratching my head.

Can confirm:
![image](https://user-images.githubusercontent.com/71730062/102130607-e1dc4580-3e05-11eb-8290-675abeda46e2.png)

I even have my card and Paypal linked to my account and it still shows this error.

**Comment by noto-rious** [comment]
Something was posted to another repo about this issue earlier this morning. Their claim is that this message is a false positive in relation to the xbox promo codes for 3 months nitro for $1. They go on to say that this is basically a case where people are posting these codes as redeemable gifts when they are in fact not redeemable via the regular discord api.

Here's a link to the comment if anyone wants to read further, still not sold on that theory but it may be correct:
https://github.com/Vedza/NitroSniperGo/issues/36#issuecomment-748493085

**Comment by noto-rious** [comment]
> 
> 
> Something was posted to another repo about this issue earlier this morning. Their claim is that this message is a false positive in relation to the xbox promo codes for 3 months nitro for $1. They go on to say that this is basically a case where people are posting these codes as redeemable gifts when they are in fact not redeemable via the regular discord api.
> 
> Here's a link to the comment if anyone wants to read further, still not sold on that theory but it may be correct:
> [Vedza/NitroSniperGo#36 (comment)](https://github.com/Vedza/NitroSniperGo/issues/36#issuecomment-748493085)

![proof](https://user-images.githubusercontent.com/69278774/103502978-8c012900-4e18-11eb-84db-e926fc29bdc2.png)

So I finally got the error on another account and then tried the code on my legit account and the picture above was the server response. It would seem as if the error is indeed linked in with the 3 month promo they have with microsoft, as I have purchased it on one account and not the other. Closing this issue for good!
