### ISSUE TITLE
yelp

### ISSUE THREAD

**Issue by razzviruz** [noto-rious/Nitro.Self-V3#9]
go get https://gopkg.in/noto-rious/Nitro.Self-V3.v3
package https:/gopkg.in/noto-rious/Nitro.Self-V3.v3: https:/gopkg.in/noto-rious/Nitro.Self-V3.v3: invalid import path: malformed import path "https:/gopkg.in/noto-rious/Nitro.Self-V3.v3": invalid char ':'

**Comment by noto-rious** [comment]
`go get github.com/noto-rious/Nitro.Self-V3`
